<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AlipayOrder extends Model
{
    use HasFactory;
    protected $table = 'alipay_order';
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->{static::CREATED_AT} = time();
        });

        static::updating(function ($model) {
            $model->{static::UPDATED_AT} = time();
        });
    }

    protected $fillable = [
        'sn',
        'price',
        'status',
        "pay_time",
        "alipay_sn",
        "status",
    ];

    // 白名单
    protected $guarded = [

    ];

    protected $appends = [
        "StatusText"
    ];

    public function getStatusTextAttribute(){
        return $this->attributes['status'] ?? 0 == 1 ? "已支付" : "未支付";
    }




}
